### PR TITLE
fix for to being off by one

### LINKED ISSUE #157: Off by one error in blacklight gallery slideshow #2567
Example: https://exhibits.stanford.edu/bacon/catalog?q=&search_field=search&view=slideshow
Clicking on the first result in the slideshow opens the second, and so on.

This seems related to whether version 2 or 3 of view_component is being used.

See:
https://github.com/search?q=repo%3Aprojectblacklight%2Fblacklight%20COLLECTION_INDEX_OFFSET&type=code
https://github.com/projectblacklight/blacklight-gallery/commit/03721c40297be61babf4190d16a591f66dc7e7c2#diff-2014cfde3b1fa7bf929fade26c45c1a9a4328199617a56400c85b806e21f3964R7

Updating exhibits to view_component v3 should fix this (https://github.com/sul-dlss/exhibits/issues/2563), but any app still using v2 is impacted.

### PR DESCRIPTION
**Pull request by dnoneill**
closes #157 

problem caused by https://github.com/projectblacklight/blacklight-gallery/commit/03721c40297be61babf4190d16a591f66dc7e7c2#diff-2014cfde3b1fa7bf929fade26c45c1a9a4328199617a56400c85b806e21f3964R7

### CODE REVIEW

File: app/components/blacklight/gallery/slideshow_preview_component.rb [hunk 1]
```diff
@@ -7,7 +7,8 @@ class SlideshowPreviewComponent < Blacklight::DocumentComponent
 
       def initialize(document:, document_counter: nil, **args)
         super(document: document, document_counter: document_counter, **args)
-        @document_counter = document_counter || @counter
+        # Items in JS start at 0. https://github.com/projectblacklight/blacklight-gallery/blob/main/app/assets/javascripts/blacklight_gallery/slideshow.js#L61
```
Comment (jcoyne) [inline app/components/blacklight/gallery/slideshow_preview_component.rb:10]: Doesn't this depend on which version of ViewComponent you are running?
https://viewcomponent.org/CHANGELOG.html#v300

> BREAKING: Change counter variable to start iterating from 0 instead of 1.

**Review by jcoyne — CHANGES_REQUESTED** [review]

File: app/components/blacklight/gallery/slideshow_preview_component.rb (hunk 1 above)
Comment (dnoneill) [reply app/components/blacklight/gallery/slideshow_preview_component.rb]: It does. Finally figured it out. Change has been pushed.

File: app/components/blacklight/gallery/slideshow_preview_component.rb [hunk 2]
```diff
@@ -7,7 +7,14 @@ class SlideshowPreviewComponent < Blacklight::DocumentComponent
 
       def initialize(document:, document_counter: nil, **args)
         super(document: document, document_counter: document_counter, **args)
-        @document_counter = document_counter || @counter
+        # ViewComponent 3, document_counter = 0
+        # ViewComponent 3, @counter = 1
+        # ViewComponent 3, COLLECTION_INDEX_OFFSET = 1
+
+        # ViewComponent 2, document_counter = 1
```
Comment (jcoyne) [inline app/components/blacklight/gallery/slideshow_preview_component.rb:14]: Can you add a view_component 2 and 3 configuration to the CI config so that both ways are adequately tested?  Do we still need to support VC 2?

**Review by jcoyne — CHANGES_REQUESTED** [review]

File: app/components/blacklight/gallery/slideshow_preview_component.rb (hunk 2 above)
Comment (dnoneill) [reply app/components/blacklight/gallery/slideshow_preview_component.rb:14]: We have apps still using VC2. We want to continue to support.

File: .github/workflows/ruby.yml [hunk 3]
```diff
@@ -19,12 +19,19 @@ jobs:
...
         additional_name: [""]
+        view_component_version: ["~> 3.12"]
         include:
           - ruby: "3.1"
             rails_version: 6.1.7
             blacklight_version: "~> 7.0"
             experimental: false
             additional_name: Rails 6.1, Ruby 3.1
+          - ruby: "3.1"
+            rails_version: 6.1.7
```
Comment (jcoyne) [inline .github/workflows/ruby.yml:30]: Why add this with a deprecated version of rails  and ruby?

Comment (dnoneill) [reply .github/workflows/ruby.yml:30]: Right now I am just trying to get ViewComponent2 to install, which isn't working.

File: app/components/blacklight/gallery/slideshow_preview_component.rb [hunk 4]
```diff
@@ -7,7 +7,14 @@ class SlideshowPreviewComponent < Blacklight::DocumentComponent
...
+        # ViewComponent 2, @counter = 1
+        # ViewComponent 2, COLLECTION_INDEX_OFFSET = 0
+        @document_counter = document_counter ? document_counter + (COLLECTION_INDEX_OFFSET - 1) : @counter - 1
```
Comment (jcoyne) [inline app/components/blacklight/gallery/slideshow_preview_component.rb:17]: Is the problem here that the slide number is using `@document_counter`, but it should use `@counter` instead? Isn't this adjustment already done by  https://github.com/projectblacklight/blacklight/blob/d25f695fbfd377983afe15f90e011509e12e977f/app/components/blacklight/document_component.rb#L111 ?   Can we remove all of this code an rely solely on what Blacklight provides?

Comment (dnoneill) [reply app/components/blacklight/gallery/slideshow_preview_component.rb:17]: I mean yeah that would work, we would have to do counter - 1 because we want to start at 0, not 1 which is what blacklight does. I figured there was probably a good reason to use document_counter first instead of @counter which is why I didn't change it.

Comment (jcoyne) [reply app/components/blacklight/gallery/slideshow_preview_component.rb:17]: I think it's a bit dangerous to reset instance variables that are originally set by the parent class. I think it's much safer to create a new variable if you can't use `@counter`.

Comment (dnoneill) [reply app/components/blacklight/gallery/slideshow_preview_component.rb]: Also I am pretty sure I am going to have to rewrite a bunch of tests to get this to work in vc2. It looks like vc_test_controller doesn't exist in vc2

Comment (dnoneill) [reply app/components/blacklight/gallery/slideshow_preview_component.rb]: Figured it out.

File: spec/components/blacklight/gallery/slideshow_preview_component_spec.rb [hunk 5]
```diff
@@ -51,6 +51,14 @@
       expect(rendered).to have_selector '.thumbnail img[@src="http://example.com/image.jpg"]'
     end
 
+    it 'renders the correct slide number' do
+      if VIEW_COMPONENT_VERSION < 3
+        expect(rendered).to have_css '[data-slide-to=\"4\"][data-bs-slide-to=\"4\"]'
```
Comment (jcoyne) [inline spec/components/blacklight/gallery/slideshow_preview_component_spec.rb:56]: Isn't the idea that these numbers should be the same regardless of what version of VC is used?

Comment (dnoneill) [reply spec/components/blacklight/gallery/slideshow_preview_component_spec.rb:56]: Not in the component.  

It inherits from https://github.com/projectblacklight/blacklight/blob/v8.4.0/app/components/blacklight/document_component.rb#L26C1-L26C72

VIEW_COMPONENT_VERSION = 2, then the COLLECTION_INDEX_OFFSET = 0 
VIEW_COMPONENT_VERSION = 3,  then the COLLECTION_INDEX_OFFSET = 1

VIEW_COMPONENT_VERSION = 2, @count = 0 + 5 (document_counter, which we set in the test)
VIEW_COMPONENT_VERSION = 3, @count = 1 + 5 (document_counter, which we set in the test)

The component removes - 1 so it is right.

Comment (jcoyne) [reply spec/components/blacklight/gallery/slideshow_preview_component_spec.rb:56]: Okay, so because the input will be different for each version, it's going to result in the same output.

**Review by jcoyne — APPROVED** [review]
